# Generated by Django 2.2.7 on 2019-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191126_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
