# Generated by Django 2.2.7 on 2019-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191126_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='/Images/Снимок экрана 2019-11-25 в 18.42.23.png', upload_to=''),
        ),
    ]
